Fitness_Journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Fitness_Journal.web.views import custom_404,custom_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Fitness_Journal.web.urls')),
    path('authorization/', include('Fitness_Journal.app_auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404
handler500 = custom_500

Fitness_Journal/web/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from Fitness_Journal.app_auth.models import AppUser
from django.db.models.signals import post_save
from django.dispatch import receiver
UserModel = get_user_model()


class Profile(models.Model):
    first_name = models.CharField(
        max_length=30,
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=30,
        blank=True,
        null=True,
    )
    age = models.IntegerField(
        blank=True,
        null=True,
    )
    user = models.OneToOneField(
        UserModel,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def clean(self):
        if self.age is not None and (self.age < 1 or self.age > 150):
            raise ValidationError("Age must be between 1 and 150.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

@receiver(post_save, sender=UserModel)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=UserModel)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()


class Meal(models.Model):
    user = models.ForeignKey('app_auth.AppUser', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class MealPlan(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f"{self.user.username}'s Meal Plan - {self.date}"


class MealEntry(models.Model):
    meal_plan = models.ForeignKey(MealPlan, on_delete=models.CASCADE,primary_key=False)
    meal_name = models.CharField(max_length=100)

    def __str__(self):
        return self.meal_name


class UserProfile(models.Model):
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    meal_data = models.CharField(max_length=200, blank=True, null=True)


class ProgressPhoto(models.Model):
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='static/')
    caption = models.CharField(max_length=30)
    upload_date = models.DateTimeField(auto_now_add=True)


class Workout(models.Model):
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    date = models.DateField()
    workout_type = models.CharField(max_length=100)
    duration_minutes = models.PositiveIntegerField()
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s {self.workout_type} on {self.date}"


templates/web/addedmeal.html
{% load static %}
<html>
<head>
    <title>My Meals</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-image: url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
        }

        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;
        }

        .btn-custom:hover {
            background-color: #CC0000;
        }

        .buttons-body {
            display: flex;
            margin-bottom: 15px;
            gap: 10px;
        }
        .meal-container {
            display: flex;
            flex-wrap: wrap;
            gap: 30px;
            margin-top: 20px;
            justify-content: flex-start;
        }

        .meal-item {
            background-color: #fff;
            color: #333;
            border-radius: 8px;
            padding: 10px;
            width: 200px;
        }
        h2 {
            color: #fff;
        }


    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>
        <div class="content">
            <h2>My Meals:</h2>
            {% if meal_plans %}
                <form method="post" action="{% url 'added_meal' %}">
                    {% csrf_token %}
                    <div class="meal-container">
                        {% for meal_plan in meal_plans %}
                            <div class="meal-item">
                                <h3>{{ meal_plan.date }}</h3>
                                <ul>
                                    {% for meal_entry in meal_plan.mealentry_set.all %}
                                        <li>{{ meal_entry.meal_name }}</li>
                                    {% empty %}
                                        <li>No meals found for this day.</li>
                                    {% endfor %}
                                </ul>
                                <input type="checkbox" name="selected_meal_plans" value="{{ meal_plan.id }}">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="button-delete">
                        <button type="submit" name="delete_selected" class="btn btn-custom mt-3">Delete Selected</button>
                    </div>
                    <div class="buttons-body">
                        <a href="{% url 'main_view' %}" class="btn btn-custom mt-3">Back</a>
                        <a href="{% url 'custom_diet' %}" class="btn btn-custom mt-3">Create a Meal</a>
                    </div>
                </form>
            {% else %}
                <div>
                    <h2>You have no added meals!</h2>
                </div>
                <div class="buttons-body">
                        <a href="{% url 'custom_diet' %}" class="btn btn-custom mt-3">Create a Meal</a>
                        <a href="{% url 'main_view' %}" class="btn btn-custom mt-3">Back</a>
                    </div>
            {% endif %}

        </div>

    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>

    </footer>
</body>
</html>

templates/web/base.html
{% load static %}
<html>
<head>
    {% if not user.is_authenticated %}
        <title>Fitness Journal</title>
    {% else %}
        <title>Fitness Journal</title>
    {% endif %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-image: url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
        }

        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;
        }
        .buttons-body {
            display: flex;
            margin-bottom: 15px;
            margin-left: 5px;
            gap: 10px;
        }
        .btn-custom-not-auth {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 40px;
            cursor: pointer;
            padding: 10px 20px;
            margin-left: 300px;
            margin-top: 40px;


        }
        .buttons-body-not-auth {
            display: flex;
            margin-left: 50px;
        }
        .home-text {
            color: #fff;
            margin-left: 20px;
            margin-top: 20px;
            font-size: 28px;
        }
        .home-text-not-auth {
            color: #fff;
            margin-left: 20px;
            margin-top: 80px;
            font-size: 21px;
        }
        .random-quote {
            color: #fff;
            margin-left: 20px;
            margin-top: 200px;
            font-size: 18px;
        }
        .arrow {
            margin-top: 20px;
            margin-left: 150px;
            width: 150px;
            height: 100px;
        }
        .white-text {
        color: white;
        }

        .btn-custom:hover {
            background-color: #CC0000;
        }
        .footer { position: fixed; top: 90%; left: 0; right: 0; bottom: 0;
      background: #ffffff; border: solid black; border-width: 2px 0 0 0; }
        .accordion-content {
            display: none;
            margin-left: 20px;
        }

        .accordion-toggle {
            cursor: pointer;
            margin-bottom: 5px;
        }

        .accordion-toggle.active {
            font-weight: bold;
        }

        .accordion-toggle.active + .accordion-content {
            display: block;
        }
        .not_found_error {
            color:red;
            margin-top: 270px;
            margin-left: 450px;
        }
        .larger-text {
            font-size: 100px;
        }
        .oops-text {
            margin-left: 250px; /* Adjust the value as needed */
        }
    </style>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-custom mt-0" href="{% url 'login_user' %}">Log in</a>
                        <a class="btn btn-custom mt-0" href="{% url 'register_user' %}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
    {% block footer %}
    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>
    </footer>
    {% endblock %}
</body>
</html>

templates/web/diet.html
{% load static %}
<html>
<head>
    <title>Form Page</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-image: url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
            color: #fff;
            padding: 20px;
        }


        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;
        }
        .buttons-body {
            display: flex;
            margin-bottom: 15px;
            margin-left: 5px;
            gap: 10px;
        }

        .btn-custom:hover {
            background-color: #CC0000;
        }
        .footer { position: fixed; top: 90%; left: 0; right: 0; bottom: 0;
      background: #ffffff; border: solid black; border-width: 2px 0 0 0; }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>


    <div class="content">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="buttons-body">
                <input type="submit" value="Submit" class="btn btn-custom mt-3">
                <a href="{% url 'main_view' %}" class="btn btn-custom mt-3">Back</a>
            </div>
        </form>
    </div>

    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>
    </footer>
</body>
</html>

templates/web/main.html
{% load static %}
<html>
<head>
    {% if not user.is_authenticated %}
        <title>Fitness Journal</title>
    {% else %}
        <title>Fitness Journal</title>
    {% endif %}


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


    <style>
        body {
            background-image: url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
        }

        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;

        }
        .buttons-body {
            display: flex;
            margin-bottom: 15px;
            margin-left: 5px;
            gap: 10px;
        }
        .btn-custom-not-auth {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 40px;
            cursor: pointer;
            padding: 10px 20px;
            margin-left: 300px;
            margin-top: 40px;


        }
        .buttons-body-not-auth {
            display: flex;
            margin-left: 50px;
        }
        .home-text {
            color: #fff;
            margin-left: 20px;
            margin-top: 20px;
            font-size: 28px;
        }
        .home-text-not-auth {
            color: #fff;
            margin-left: 20px;
            margin-top: 80px;
            font-size: 21px;
        }
        .random-quote {
            color: #fff;
            margin-left: 20px;
            margin-top: 200px;
            font-size: 18px;
        }
        .arrow {
            margin-top: 20px;
            margin-left: 150px;
            width: 150px;
            height: 100px;
        }

        .btn-custom:hover {
            background-color: #CC0000;
        }
        .footer { position: fixed; top: 90%; left: 0; right: 0; bottom: 0;
      background: #ffffff; border: solid black; border-width: 2px 0 0 0; }


    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-custom mt-0" href="{% url 'login_user' %}">Log in</a>
                        <a class="btn btn-custom mt-0" href="{% url 'register_user' %}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <div class="content">
        {% if not user.is_authenticated %}
            <p class="home-text-not-auth">
            No matter what kind of sport a person practices, it is important to<br> have his own diary in which he can keep notes on his nutrition and<br> monitor the progress of his appearance. No matter where you are<br> and what device you use the site from, Fitness Journal gives you the<br> opportunity to do these things personal! Embark on your adventure<br> now!
            </p>
            <div class="buttons-body-not-auth">
                <a href='{% url 'login_user' %}' class="btn btn-custom-not-auth">Get Started!</a>
            </div>
            <img src="{% static 'arrow.png' %}" alt="My Image" class="arrow">
        {% else %}
            <div class="buttons-body">
                <a href='{% url 'added_meal' %}' class="btn btn-custom mt-3">My Meals</a>
                <a href='{% url 'custom_diet' %}' class="btn btn-custom mt-3">Create Meal</a>
                <a href='{% url 'added_photos' %}' class="btn btn-custom mt-3">My Progress</a>
                <a href='{% url 'my_profile' %}' class="btn btn-custom mt-3">My Profile</a>
                <a href='{% url 'contacts' %}' class="btn btn-custom mt-3">Contacts</a>
            </div>
            <p class="home-text">
                Hello! Every day you take one small step towards change.<br>
                Don't wait to get motivated, because motivation comes with<br>persistence and discipline.
            </p>
            <div class="content">
                <p class="random-quote">{{ random_quote }}</p>
            </div>
        {% endif %}
            </div>
    </div>

    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>
    </footer>
</body>
</html>

templates/web/photos_page.html
{% load static %}
<html>
<head>
    <title>My Photos</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-image: url("{% static 'background.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        .title {
            color: #fff;
            margin-top: 10px;
            margin-left: 170px;
        }


        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;
        }
        .btn-custom-no-photos {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 20px;
            cursor: pointer;
            padding: 10px 20px;
        }
        .buttons-header-no-photos {
            display: flex;
            justify-content: flex-start;
            margin-bottom: 300px;
            margin-top: 50px;
            margin-left: 240px;
            gap: 10px;
        }
        .button-delete{
            margin-left: 1310px;

        }

        .btn-custom:hover {
            background-color: #CC0000;
        }

        .content {
            background-color: #343a40;
            color: #fff;
            padding: 20px;
        }
        .content  {
            border: 1.5px solid #000;
            max-width: 100%;
            height: auto;
        }
        .content img {
            max-width: 100%;
            height: auto;
            margin-top: 15px;
            margin-left: 15px;

            float: left;

        }
        .content {
            flex: 1;
            color: #fff;
            padding: 20px;
        }
        h1 {
            color: #fff;
            margin-top: 140px;
            margin-left: 170px;
         }
        .photo-container {
            margin-top: 15px;
            margin-left: 15px;
        }

        .photo-item {
            display: inline-block;
            vertical-align: top;
            margin-right: 20px;
            max-width: 500px;
            max-height: 400px;
            overflow: hidden;
        }

        .photo-description {
            color: #fff;
            text-align: center;
            margin-top: 5px;
        }
        .buttons-header {
            display: flex;
            justify-content: flex-end;
            margin-bottom: 15px;
            gap: 10px;
        }
        h1 {
            float: left;
        }


    </style>
</head>
{% if user_photos %}
<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content">
    <h1 class="title">My Photos:</h1>
    <div class="buttons-header">
        <a href="{% url 'upload_progress_photo' %}" class="btn btn-custom mt-3">Add Photo</a>
        <a href="{% url 'main_view' %}" class="btn btn-custom mt-3">Back</a>
    </div>
    <div class="photo-container">
        <form method="post" action="{% url 'added_photos' %}">
            {% csrf_token %}
            {% for photo in user_photos %}
                <div class="photo-item">
                    <img src="{{ photo.photo.url }}" alt="{{ photo.caption }}">
                    <p class="photo-description">{{ photo.caption }}</p>
                    <input type="checkbox" name="selected_photos" value="{{ photo.id }}">
                </div>
            {% endfor %}
            <div class="button-delete">
                <button type="submit" name="delete_selected" class="btn btn-custom mt-3">Delete Selected</button>
            </div>
        </form>
    </div>
</div>

    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>
    </footer>
</body>
{% else %}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>
    <body>
    <h1>No Photos Added</h1>
    <div class="buttons-header-no-photos">
        <a href="{% url 'upload_progress_photo' %}" class="btn btn-custom-no-photos">Upload Photo</a>
        <a href="{% url 'main_view' %}" class="btn btn-custom-no-photos">Back</a>
    </div>
    </body>
{% endif %}
</html>

templates/web/upload_progress_photo.html
{% load static %}
<html>
<head>
    <title>Upload Progress Photo</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        .navbar-custom, .footer {
            background-color: #FF0000;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .content {
            flex: 1;
            background-color: #343a40;
            color: #fff;
            padding: 20px;
        }

        .btn-custom {
            background-color: #FF0000;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 40px;
            font-size: 16px;
            cursor: pointer;
            padding: 10px 20px;
        }

        .btn-custom:hover {
            background-color: #CC0000;
        }


        .content  {
            border: 2px solid #000;
            max-width: 100%;
            height: auto;
        }
        .buttons-body {
            display: flex;
            margin-bottom: 15px;
            margin-left: 5px;
            gap: 10px;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
        <a class="navbar-brand" href="{% url 'main_view' %}">Fitness Journal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-custom mt-0" href="{% url 'logout_user' %}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="content">
        <h1>Upload Progress Photo</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="buttons-body">
                <button type="submit" class="btn btn-custom mt-3">Upload Photo</button>
                <a href="{% url 'added_photos' %}" class="btn btn-custom mt-3">Back</a>
            </div>
        </form>


    </div>

    <footer class="footer py-3 bg-dark">
        <div class="container">
                <div class="col-12 text-center">
                    <p class="text-white">© 2023 Fitness Journal. All rights reserved.</p>
                </div>
        </div>
    </footer>
</body>
</html>